spring:
  datasource:
    url: jdbc:h2:mem:${spring.application.name};MODE=ORACLE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        integration:
          envers:
            enabled: false
  main:
    allow-bean-definition-overriding: true
  application:
    name: bet-coupon

server:
  port: 8083
  servlet:
    context-path: /coupon
  error:
    include-stacktrace: never

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: DEBUG
    com.bet: DEBUG